/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

let a: number = 1
let b: number = 2
let c: number = 0
let addition: number = 2

for(let i: number = 2; i < 4000000; i++) {

    //  * Fibonacci value should not exceed 4 million
    if (c > 4000000) break

    // * Adding previous values
    c = a + b

    // * Calculating sum
    if (c % 2 === 0) addition += c

    // * Swapping out values for next iteration
    a = b
    b = c
}

console.log('Sum is ', addition)